### ISSUE TITLE
课程

### ISSUE THREAD

**Issue by qhangz** [liangzilixueha/HDU-Digital-Media-Technology#1]
综合课程设计是学点啥的呀？

**Comment by qhangz** [comment]
大三体制健康测试是每个学期都有嘛，然后自己在教务系统选课的嘛

**Comment by liangzilixueha** [comment]
课程设计需要你用计算机前沿小知识复刻或运行或改进一个小创意/想法。体测等待通知即可，需要去教务系统选课
[课程设计](https://github.com/liangzilixueha/HDU-Digital-Media-Technology#%E5%A4%A7%E4%B8%89%E4%B8%8B)

[体测](https://github.com/liangzilixueha/HDU-Digital-Media-Technology#%E5%85%AC%E5%85%B1%E9%80%89%E4%BF%AE%E8%AF%BE%E8%BF%99%E7%A7%8D%E8%AF%BE%E6%88%91%E5%B0%B1%E4%B8%8D%E5%8D%95%E7%8B%AC%E6%96%B0%E5%BB%BA%E4%B8%80%E4%B8%AA%E6%96%87%E4%BB%B6%E4%BA%86)

**Comment by qhangz** [comment]
好嘞谢谢！
