### ISSUE TITLE
杭电数媒2年经验分享

### ISSUE THREAD

**Issue by chaseforu** [liangzilixueha/HDU-Digital-Media-Technology#5]
# 杭州电子科技大学数字媒体技术指南
## 一.写在前头
我想写这个的原因是我在github上看到一个[杭电数媒的指南](https://github.com/liangzilixueha/HDU-Digital-Media-Technology/tree/main),对我挺有帮助的,我从大一刚入学的时候就看过这个指南.2024/7/5我大二准大三再次查看这个指南时发现他两周前提交了毕业论文并毕业了,于是我也想做一个更新(毕竟数媒的培养方案改的很频繁~~因为这专业就不好就业~~)
### 首先是与课程无关的学校经验,讲完这个后会有我大一上下和大二上下每门课的经验
1.容易挂科的课和重要的课我会标注✨
2.大一不会选课怎么办,看不懂培养计划怎么办:先把通识选修十分慢慢选了(四个部分分别是4,2,2,2分),都是些简单的课.还有能选的专业选修可以选个喜欢的
3.与吃相关
* 普通食堂是个杭电人都吃就不说了,文小二买饭需要打包费1元米饭1元,所以你想打包并省钱的话其实可以去食堂打包,每餐能省1元左右.
* 美食城好吃的可以多次购买的只有隆江猪脚饭那家,烧鸭和猪脚饭都不错就是有点油.美食城经常倒闭啥的,看来学校里的生意也没那么好做
* 杭电每年会有一次烧烤节,推荐最后一天再买会便宜很多.
* 杭电周围好吃的并且可以常吃的有塔可星taco star,19.9元一个塔可加小食加无限续杯的饮料,比麦当劳划算,比华莱士好吃

4.我们专业学的很杂,所以找工作的事情你得早点考虑(下载一个BOSS直聘的APP查看你喜欢的工作需要哪个技能),特别是不打算考研究生的同学
5.生活经验,最适合宿舍的单品是一把椅子
6.如果你学专业课感到比较吃力的话,容易过的课的老师有:林文倩,聂斌玲,徐力豪
#### 军训
1.时间:22届是8/15左右就入学军训的(下沙最早一批)
2.做好防晒没什么好说的,不做就准备脱皮吧.
3.身体问题可以申请减训,但是成绩会变成及格(我就是身体原因加站太多足底发炎了,脚部一用力就疼申请减训)(先去三甲医院开证明再去校医院开证明的证明).减训就是在旁边坐着抄杭电校规什么的,然后减训的人专门一个营
#### 高等数学B1
1.有期中期末考试
2.自学看B站框框老师的课(速成课即可),全寝公认最好的课,日常作业和期中期末都能看他.
3,期中期末试卷进HDU数学营找期中期末试卷(群号:682906443)
#### 线性代数
1.有期中期末考试
2.自学看B站框框老师的课(速成课即可),全寝公认最好的课,日常作业和期中期末都能看他.
3,期中期末试卷进HDU数学营找期中期末试卷(群号:682906443)
#### C语言程序设计
1.老师:周志光.他是研究可视化和数字孪生相关的.~~个人觉得可视化还行,数字孪生我感觉挺没意义的(听着高大上成品就是开源3D引擎加定制小功能),不过确实有冤种国企订购~~
2.平时课上就让你写题目,在一个类似国产leetcode的平台里,有手机用不会写就抄,但最后都要会做毕竟要期末考
3.有期末考试,是上机写代码,难度和平时差不多.要复习的话就复习一下平时课上写的题即可.
#### 体育-太极
1.大一上每个人都必学的体育课
2.有期末考试,B站有相关视频,期末考试前跟着学动作
3.我印象中期末考试第一次打的不好老师是可以让你打第二次的
#### 大学英语精读1B
1.22届高考英语130以上是A班,也就是大学英语精读1A,我这是B班,高考英语126,两个班其实没区别
2.老师:邱元英,老师很好,平时分90+
3.有期末考试,但是完全不用准备,有高中基础即可
#### 大学英语听说1B
1.老师:钱昕燕,这个老师也很好,平时分90+
2.有期末考试,考试就是让你和你一个朋友对话就行,十分钟内就结束了,简单不用准备
#### 思想道德与法治
应该挺水挺简单的,没啥印象了
#### 新媒体类学科导论
学习通的课,没有实体课而且是入学前就有,就把网课刷一刷有题目做一下就行
#### 观测地球的遥感技术(通识选修)
1.有两个老师,一个年轻另一个年纪稍微大点
2.平时课上就讲讲遥感相关技术
3.期末写一篇遥感相关的论文
#### 科学之美(通识选修)
1.这门课只有一学分,我不推荐选,当时年少无知
2.只要听各种领域的讲座即可,每节课老师都不一样
3.上完所有讲座后谈两个印象比较深的讲座和体悟什么的,简单
#### 高等数学B2
1.有期中期末考试
2.自学看B站框框老师的课(速成课即可),全寝公认最好的课,日常作业和期中期末都能看他.
3,期中期末试卷进HDU数学营找期中期末试卷(群号:682906443)
#### C++面向对象程序设计
容易挂科✨
1.老师:尹学松,数媒院长
2.课上没啥压力,偶尔做做题
3.除了c++基础外参杂着教了一些数据结构的内容
4.期末考试准备的话要把他教到的地方从c++基础到部分数据结构都网课看一遍
5.期末考试试卷是全英文的,学一下C++中概念的英语单词,不然题目都看不懂
#### 高级C编程
1.老师:陶秀挺,额挺和蔼的
2.课上是不讲C语言基础的,主要是讲一些用C语言一些库做的小游戏,有一些平时作业什么的,也比较简单
3.期末是大作业,我就对着B站的教程做一个简易的飞机大战,需要验收,验收前你把代码读懂然后把代码逻辑讲给他听就行,不会为难你
#### 平面制作课程设计
1.老师:林文倩,我愿称之为学院最佳老师,基本都能让你的专业课满绩
2.课上教一下PS和AI的使用,平时上交一些功能的作业,期中期末分别交一下PS和AI的大作业,简单的
#### 创业管理(通识必修需要抢课)
1.有平时作业,是小组作业
2.也有期末大作业,也是小组作业
#### 体育-篮球(需要抢课)
1.老师:陈传令,课上没啥压力,下雨就放,管着一个学校女子篮球队,带队出省还能给我放假
2.期末就是比中考篮球简单一点的考试,"日"的左边运球到底下投篮接住篮球再运球的"日"的右边再到底下投篮接住篮球运球到"日"的左边结束("日"是篮球场)
#### 网页前端技术
1.老师:杨根福,人挺不错的
2.课上就一点点从HTML讲到CSS再讲到JS前端三大件然后再讲ES6和Ajax之类的(后面这两个比较难,我当时才大一很多课,而且这部分过的很快也没学明白)
3.期末做一个大作业,他要求是要用到ES6和Ajax,主题是做一个人工智能手机APP网页前端,但我不会没学明白就做了一个静态网页三个主界面这样(近一半人都这样),但还是有很多大佬ES6和Ajax学会的.
4.大作业要验收,由于我其实没完全完成他的任务,所以稍微被批评了一下,但我期末也有80分(现在我这种垃圾大作业AI都能做了)
#### 大学英语精读2B
1.老师:邱元英,老师很好,平时分90+
2.有期末考试,但是完全不用准备,有高中基础即可
#### 大学英语听说2B
1.老师:钱昕燕,这个老师也很好,平时分90+
2.有期末考试,考试就是让你和你一个朋友对话就行,十分钟内就结束了,简单不用准备
#### 中国近现代史纲要
老师会给题库,考试前看一下题库就行了或者登录杭电期末刷题的网站刷题
#### 社会主义发展史
1.老师:马晓媚,有点事多,一直让人回答和讨论什么的,还对学生坐的位置有意见
2.期末考试刷题库或靠政治正确答题
#### 其他不是很重要的课
* 形式与政策2(无考试)
* 大学生心里教育健康(有考试和刷网课)
#### 数据结构
重要✨,容易挂科✨
1.老师:刘玉华,老师很好对学生管的不严,期末最后的课也会给你过一下知识点
2.这应该是大学里最有用的一门课吧,推荐好好学,哪都要用到,如后面的算法设计与分析
3.期末的话B站课程很多,github上也可以搜到往年的试卷
#### 计算机图形学
很容易挂科✨✨
1.听说是挂科率最高的课
2.老师:曹伟娟,她教两个班(还有一个计算机图形学老师也教一个班吧),曹伟娟一个班给的平时分高另一个低,她有两套平时分系统,学习通那套高,在浙学加慕课那套低.我推荐如果你开学这门课发现你是慕课班直接退了选另一个班.学习通那套平时分的班平时分普通90+
3.作业都是互评,所以请和同学打好关系啊(我大学两年里但凡互评都是给满分的)
4.有个大作业,手搓一个光线追踪离线3D渲染.推荐学习教程ray tracing in one weekend和作者下一部ray tracing in next week(知乎csdn百度搜索这两个教程的英文名就有中文翻译版本).把这两个教程学完就能做一个完美的大作业,能力不足就边学边抄这两个教程吧.(但是这两个教程没有讲到如何导入模型,大作业是有贴图,各种材质,各种光源(光源本质上也是材质的一种,点光就是个球形加灯光材质,面光就是平面加灯光材质),各种模型的要求的)
5.有期末考试而且是全英文的,包含图形学基础知识,用矩阵进行坐标换算等(剩下不太记得了),最后一题是关于硬阴影(边界分明)和柔和阴影,配图是太阳射到一个球体形成一些阴影.推荐教程:【【计算机图形学】期末复习-哔哩哔哩】 https://b23.tv/mcBbPFu 印象中要考到的计算题这里都提到了
6.因为没有泄露的期末试卷所以复习起来也很困难,网上相关性高的教程也很少,所以比较容易挂科.但你是曹伟娟学习通班就好很多,平时分90+,我有个室友期末考了28分也运气好过了.
#### 三维建模技术
1.老师:林文倩,基本接近满绩
2.课上学习blender(免费开源建模软件)的相关用法,期末做一个大作业有一个特定的主题展示你的blender技能
#### 图像处理与分析
1.老师:王勇
2.老师平时是点名签到的,一学期会点五次
3.课上讲的很难很难但是期末考其实很简单,把学习通平时的作业都看一遍,期末考试90%都是学习通原题,30分钟出来就能90+
#### 数据结构课程设计
和数据结构同一个老师,课上就让你写题目,然后把错的多的题目讲一下
#### 数字媒体后期制作
1.老师林文倩
2.课上就讲一下AE的使用方法和一个比较重要的插件saber
3.有个人作业,小组作业,期末大作业.按要求即可,林文倩老师会给你高分的
#### 概率论和数理统计
1.有期中期末考试
2.自学看B站框框老师的课(速成课即可),全寝公认最好的课,日常作业和期中期末都能看他.
3,期中期末试卷进HDU数学营找期中期末试卷(群号:682906443)
#### 其他课程
* 陶瓷艺术赏析与体验(通识选修):我唯一上过的网课,在周六6-9节
* 习近平新时代中国特色社会主义思想概论:跟其他一样刷一下题目即可,不刷都行,往政治正确的方向选,简答题永远都是谈谈你课上印象最深的部分
* 形式与政策3:最后一节课写个论文,AI完成即可
* 中医防治疾病的思维及原理(通识选修.老师:王彦刈,这老师思想好像有点问题,课上一直会让学生说中医比西医哪里哪里优秀,然后中医用暗物质起作用啥的,不过期末考很简单,甚至可以用手机搜,课上考试我15分钟就走了)
* 数字经济时代的大学生职业素养(通识选修.老师:毛崇峰.事情有点多不推荐,但分数不会低)
* 人工智能中的法律问题(通识选修.老师:宁利昂.通识选修里我上过比较喜欢的一门,除了期末一个手写2000字的小论文,谈谈课上感兴趣的部分以外没啥作业,课程内容我感觉比较有收获,毕竟没学过法律)
#### 操作系统
容易挂科✨
1.老师:赵伟华,人很好,很尽责,但我希望比较难的课能水点哈哈
2.每节课要用在浙学签到,课上时不时就要做一个限时题目或者小组作业而且算平时分,压力有点大
3.这门课小组回答老师问题也算平时分,所以必须回答,虽然大部分是课本原话,但是逼你回答就很烦,每次四节课回答机会还是很多的
4.有实验部分并且要验收,实验难度较高(但是百度可以搜到前人的代码,关键词HDU操作系统实验),我验收也支支吾吾不太回答得出来代码为什么这么写.实验是关于Linux系统的实验,虽然难度高但是去验收的时候代码能运行就有60分,甚至不会答她任何问题也是可以的(我室友就这样).几乎每行代码都会问你作用,全部回答上来就满分,差一两个就验收八九十分
5.期末考试难度和课上难度差不多,操作系统的试卷是数媒的老师出的,和CS计算机科学与技术的试卷不一样,网上能找到的都是CS的试卷
#### 游戏程序设计
1.老师:李仕,挺好说话
2.平时所有作业都是互评作业,每周2-4个,都与期末考试有关,可以认真做一下
3.有期末考试,但90%都是学习通作业的原题,所以考试前把所有学习通原题看一遍答案即可.最后一题考了BAG10问题,是唯一一个不是学习通原题的.
4.期末要提交四个案例的代码(但老师说只要你考及格了他就不会看,只有考不到及格的人才会看看你平时做了什么),分别是
* C++控制台贪吃蛇
* SFML贪吃蛇
* SFML扫雷
* SFML俄罗斯方块
所有课程内容都是围绕上面四个案例来的
#### 游戏程序设计课程设计
1.老师同上
2.写一个SFML棋牌类的游戏,我做的是飞行棋(也是最多人做的),验收很简单,给他看一下运行一下就行,问问你的创新点,验收甚至不涉及代码部分
#### 英语应用文写作(通识必修,要抢)
1.老师:党兆颖,老师很好,全寝上的都是她的英语通识必修课
2.课上没啥任务,要做的任务她都让你用AI完成就行,她用的是讯飞星火
3.有期末考试,期末考没啥难度,不太需要复习
#### 毛泽东思想和中国特色社会主义理论体系概论
没啥好说的,想高分就刷题库,没打算高分就裸考就行,往政治正确那方面选随便70+
#### 数字音视频技术
1.老师:徐力豪,老师人很好
2.平时课上很少有问题,课上比较轻松
3.要做实验,难度稍微有点大,不过基本都有详细的过程说明,照着来就行,不行上AI
4.有期末考试,把老师发PPT和考点word对照着看一遍就行,难度中等吧,平时分90+不用怕挂科.
#### 界面设计
1.老师:林文倩,不必多言
2.课上就讲一下figma或即时设计的使用,一周或两周来一次个人作业或小组作业
3.期末有大作业,做一个有APP版和网页版的界面设计,每个版本至少6张有效内容(除去404页,登录页等)
#### 算法设计与分析
1.老师:聂斌玲,老师人很好
2.一个学期总共也就5此平时作业,也就是期末考试的题库了
3.期末考试全部都是学习通原题,把学习通的题目搞懂就行
#### 其他课程
* 大学生职业发展与就业指导2
* 形势与政策4
### 大三上
最后一次课多的学期了,之后就没有每学期至少16学分的要求了,也就是基本没啥课了.去忙着找工作或考研以及毕业吧
### 大四下
以上待补充

**Comment by liangzilixueha** [comment]
感谢你的添加，我会尽快整理你的评论到正文中的

**Comment by liangzilixueha** [comment]
大部分内容已添加，极少数重复的将不会被加入。此外，该分享将被置顶
